FROM node:22-alpine AS build
WORKDIR /app
COPY src/frontend/wellness-center/package*.json ./
RUN npm install
COPY src/frontend/wellness-center .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist/wellness-center/browser /usr/share/nginx/html
EXPOSE 80
