name: ci-frontend

on:
  pull_request:
    paths:
      - 'src/frontend/wellness-center/**'
      - '.github/workflows/ci-frontend.yml'
  push:
    branches: ["main", "work"]
    paths:
      - 'src/frontend/wellness-center/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  build-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend/wellness-center
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm install --no-audit --no-fund
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless
